!!com.appdynamics.cloud.prometheus.config.ServiceConfig

debugLogging: false
eventsServiceEndpoint: "https://analytics.api.appdynamics.com:443"
eventsServiceApikey: ""
controllerGlobalAccount: ""
prometheusUrl: "https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-xxxxxxx-186e-xxxx-926b-xxxxxxxxx/api/v1/query"
authenticationMode: "awssigv4"    # options are ( none | awssigv4 )
awsRegion: "us-west-2"            # mandatory if authenticationMode = awssigv4
awsAccessKey: ""                  # mandatory if authenticationMode = awssigv4
awsSecretKey: ""                  # mandatory if authenticationMode = awssigv4
  
analyticsEventsSources:
  - schemaName: "prom_node_metrics"
    schemaDefinitionFilePath: "/opt/appdynamics/appd-prometheus/conf/prom_node_metrics_schema.txt"
    queriesTextFilePath: "/opt/appdynamics/appd-prometheus/conf/prom_node_metrics_queries.txt"
    eventsSourceClass: "com.appdynamics.cloud.prometheus.analytics.PrometheusEventsSource"
    executionInterval: "5"  # executionInterval (is in minutes, whole numbers only)
    
    
  - schemaName: "prom_kubelet_metrics"
    schemaDefinitionFilePath: "/opt/appdynamics/appd-prometheus/conf/prom_kubelet_metrics_schema.txt"
    queriesTextFilePath: "/opt/appdynamics/appd-prometheus/conf/prom_kubelet_metrics_queries.txt"
    eventsSourceClass: "com.appdynamics.cloud.prometheus.analytics.PrometheusEventsSource"
    executionInterval: "5"  # executionInterval (is in minutes, whole numbers only)


